Load config from env file properly

diff --git a/Violet/makefile b/Violet/makefile
--- a/Violet/makefile
+++ b/Violet/makefile
@@ -1,22 +1,33 @@
 SHELL=bash
+ENV_FILE=.env
+ENV_PATH=../$(ENV_FILE)
 
 $(shell \
-	{ \
-		envFile=".env"; \
-		envPath="../$$envFile";  \
-		\
-		if [ ! -f "$$envPath" ]; \
-		then \
-			echo "The environment file \`$$envFile\` could not be found!"; \
-			echo "Please enter all necessary settings in the newly created $$envFile file located at $$(realpath --relative-to "$$(pwd)" "$$envPath")."; \
-			cp ../.env.template "$$envPath"; \
+	envFile=".env"; \
+	envPath="../$$envFile";  \
+	\
+	if [ ! -f "$$envPath" ]; \
+	then \
+		{ \
+			echo "The environment file \`$(ENV_FILE)\` could not be found!"; \
+			echo "Please enter all necessary settings in the newly created $(ENV_FILE) file located at $$(realpath --relative-to "$$(pwd)" "$(ENV_PATH)")."; \
+			cp ../.env.template "$(ENV_PATH)"; \
 			false; \
-		else \
+		} 1>&2; \
+	fi;)
+
+define loadPathConfig
+	$(or
+		$(shell \
 			set -o allexport; \
-			. "$$envPath"; \
+			. "$(ENV_PATH)"; \
 			set +o allexport; \
-		fi; \
-	} 1>&2)
+			cd "$$(dirname "$(ENV_PATH)")"; \
+			if [ ! -z "$$$(1)" ]; \
+			then \
+				echo "$$(realpath -m "$$$(1)")"; \
+			fi),$(2),$(3))
+endef
 
 ifneq ($(.SHELLSTATUS),0)
 $(error Warning: Please review the console output for more information)
@@ -65,7 +76,7 @@ MAPTILESETGRITFLAGS=-gu32 -gzl -gB 4 -gt -m! -p!
 
 BLDPATH=bld
 BLDROM=$(BLDPATH)/violet.gba
-BASEROM ?= base/bprd.gba
+BASEROM := $(call loadPathConfig,BASEROM,$(BASEROM),base/bprd.gba)
 MAPPROJ=proj.pmp
 SYMBOLDUMP=$(BLDPATH)/symbols
 BASESYMBOLS=bprd.sym
@@ -76,8 +87,8 @@ PKLPATH=pkl
 MOVESETPKL=$(addprefix $(PKLPATH)/, $(addsuffix .pkl, $(shell tools/pokemon_move_generator/get_species.py $(MAPPROJ) $(SPECIESCONSTANTTABLE))))
 
 # Soundfont ripper
-PSG_DATA ?= psg_data.raw
-GOLDENSUN_SYNTH ?= goldensun_synth.raw
+PSG_DATA ?= $(call loadPathConfig,PSG_DATA,$(PSG_DATA),psg_data.raw)
+GOLDENSUN_SYNTH ?= $(call loadPathConfig,GOLDENSUN_SYNTH,$(GOLDENSUN_SYNTH),goldensun_synth.raw)
 
 rwildcard=$(wildcard $1$2) $(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2))#
 
@@ -152,9 +163,6 @@ define build_list
 endef
 
 .PHONY: all clean soundfont test
-
-test:
-	@echo $(BASEROM)
 
 $(CONSTANTSHAS): include/as/%.s: %.const
 	$(shell mkdir -p $(dir $@))
